name: Attach Zip to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the project
        run: zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}.zip . -x "*.git*" -x "node_modules/*" -x ".env*" -x ".github/*"

      - name: Attach the zip file to the release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
